### ISSUE TITLE
Update Gitlab deployment automation to parameterize the version to deploy

### ISSUE THREAD

**Issue by murphyj21** [plus3it/dotc-gitlab#16]
Update the Gitlab deployment automation to parameterize the version of Gitlab to deploy.  The primary reason is to control when version upgrades take place vs. ami updates.

**Comment by ferricoxide** [comment]
Intention will be to simply add an `rpmname` parameter. That way, if a person cares to fixate on a specific version, they specify (e.g.) `gitlab-ce-10.0.3`. If they don't care what version, then they only need specify `gitlab-ce` (and yum will figure the rest out). This may also make automation more portable if switching from CE to Enterprise.

**Comment by murphyj21** [comment]
I think this is a good approach. 

Is it worth the effort to put in a check that throws an error if it's updating to a major release? 

**WARNING** - *Hey dumbass this isn't a minor update and it may shit the bed!*

**Comment by ferricoxide** [comment]
Since the model is "redeploy to upgrade", there's not a good way for it to know that it's upgrading _anything_.
